### ISSUE TITLE
Build plugin example script

### ISSUE THREAD

**Issue by forestnd** [stevenaldinger/decker#21]
Hay first really like this idea, been playing around with it for some time. 

Would love some more examples on how to use the build_plugin script. Or how to create the <plugin>.so file.

**Comment by stevenaldinger** [comment]
Hey! Thanks for checking it out and thanks for your kind words!

I think what you're going to end up wanting to use is the [decker-plugin repo](https://github.com/stevenaldinger/decker-plugin) but it's out of date at the moment and will not be compatible with some breaking updates I made to decker. I'll update it soon and include a lot more documentation on plugin development too. Thanks for calling this out as an issue!

**Comment by forestnd** [comment]
Ok that be grate. Thanks
